# Generated by Django 3.0.3 on 2020-08-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_auto_20200802_2006'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('pages', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=13)),
                ('lent', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(to='author.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
            ],
        ),
    ]
