# Generated by Django 3.0.3 on 2020-08-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_calendar', '0001_initial'),
        ('review', '0001_initial'),
        ('publisher', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='calendars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_calendar.BookCalendar'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='publisher.Publisher'),
        ),
    ]
