# Generated by Django 3.0.3 on 2020-08-09 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserved', models.DateField(default=django.utils.timezone.now)),
                ('date_returned', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
